
CFLAGS=-Wall -g -std=c99

binaries=day1 day1_part2 day2 day2_part2

all: clean $(binaries)

clean:
	-rm -f *~ 
	-rm -f *.o
	-rm -fr *.dSYM
	-rm -f $(binaries)

day1: day1.c

day1_part2: day1_part2.c

day2: day2.c

day2_part2: day2_part2.c

