CC=gcc
CFLAGS=-g -pendatic -Wall -c99
#LDFLAGS=-lcunit

all: karate_chop weather
clean:
	-rm a.out *.o karate_chop

karate_chop: karate_chop.c test_karate_chop.c
weather: weather.c 
football: football.c
